<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYn1sDLD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYn1sDLD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYn1sDLD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYn1sDLD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYn1sDLD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yn1sDLD',
    'container.build_id' => 'ab6277e7',
    'container.build_time' => 1698230685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYn1sDLD');
