<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvHx7Cf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvHx7Cf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvHx7Cf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvHx7Cf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvHx7Cf\App_KernelDevDebugContainer([
    'container.build_hash' => 'XvHx7Cf',
    'container.build_id' => '879c7235',
    'container.build_time' => 1698089356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvHx7Cf');
