<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLN4u3Xl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLN4u3Xl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLN4u3Xl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLN4u3Xl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLN4u3Xl\App_KernelDevDebugContainer([
    'container.build_hash' => 'LN4u3Xl',
    'container.build_id' => 'c9d17406',
    'container.build_time' => 1698222000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLN4u3Xl');
